import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1c1c1c",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1c1c1c",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1c1c1c",
    padding: 20,
  },
  errorText: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
    marginBottom: 20,
  },
  backButton: {
    backgroundColor: "#e74c3c",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  backIconContainer: {
    position: "absolute",
    top: 40,
    left: 20,
    zIndex: 10,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    padding: 2,
  },
  backdropImage: {
    width: width,
    height: width * 0.6,
    resizeMode: "cover",
  },
  posterContainer: {
    flexDirection: "row",
    marginTop: -80,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  posterImage: {
    width: width * 0.35,
    height: width * 0.35 * 1.5,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#333",
  },
  noPosterContainer: {
    width: width * 0.35,
    height: width * 0.35 * 1.5,
    borderRadius: 8,
    backgroundColor: "#333",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#555",
  },
  noPosterText: {
    color: "#999",
    fontSize: 14,
    textAlign: "center",
  },
  infoContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  title: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 5,
  },
  tagline: {
    color: "#aaa",
    fontSize: 16,
    fontStyle: "italic",
    marginBottom: 10,
  },
  detailText: {
    color: "#ddd",
    fontSize: 15,
    marginBottom: 5,
  },
  overviewTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
  },
  overviewText: {
    color: "#ccc",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 20,
  },

  addReviewContainer: {
    backgroundColor: "#2a2a2a",
    borderRadius: 10,
    padding: 15,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: "#444",
  },
  addReviewTitle: {
    color: "#e74c3c",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  ratingInput: {
    backgroundColor: "#3a3a3a",
    color: "#fff",
    fontSize: 16,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#555",
    textAlign: "center",
    width: "50%",
    alignSelf: "center",
  },
  commentTextInput: {
    backgroundColor: "#3a3a3a",
    color: "#fff",
    fontSize: 16,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#555",
    minHeight: 100,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: "#e74c3c",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    paddingBottom: 5,
  },
  commentContainer: {
    backgroundColor: "#2a2a2a",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#444",
  },
  commentAuthor: {
    color: "#e74c3c",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  commentText: {
    color: "#ccc",
    fontSize: 14,
    lineHeight: 20,
  },
  commentDate: {
    color: "#999",
    fontSize: 12,
    marginTop: 5,
    textAlign: "right",
  },
  noCommentsText: {
    color: "#aaa",
    fontSize: 15,
    textAlign: "center",
    paddingVertical: 20,
  },
});

export default styles;
